### ISSUE TITLE
Feature: User can view poke-list

### ISSUE THREAD

**Issue by m-Cho1** [m-Cho1/ajax-project#1]
## ⚙️ Feature

> ##### 

User can view list of Kanto Region pokemon images.
## 📐 Functionality

> ##### 

Users can view list of images of Kanto Region pokemon when they load the page.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/96744088/163846897-9f7dceac-dbd9-41fb-b27f-9af5581454f9.png)
![image](https://user-images.githubusercontent.com/96744088/163846967-aeefcf6a-afce-46a4-9b0b-3d2d2961c685.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create `<div>` element with `class="img-container"` in the HTML for image container.
- [x] Create `<ul id="poke-list">` element under `<div>` for rendering pokemon images.
- [x] Create navbar in the header section, add CSS position: fixed.
- [x] Add Pokémon logo on the right corner, and pokelist on the left corner.
- [x] Define a function that returns a DOM tree that matches with the wireframe. List of pokemon images in the card container. Make sure that the DOM tree starts with `<li>` element.
- [x] Append the  DOM tree to ul element.
- [x] Query the DOM for the `#poke-list` element.
- [x] Access the pokemon images from api.co/api/v2/, getting the first 150 pokemons.
- [x] Create a loop to access images of pokemon, then add each image to `<li>` element.
- [x] Add media query for responsive page.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
