### ISSUE TITLE
Feature: User can click on a pokemon to see details

### ISSUE THREAD

**Issue by m-Cho1** [m-Cho1/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can view details of pokemon

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can read about details of pokemon they clicked from the list, and go back to list once they are done reading details.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/96744088/164141157-7aa3ce1b-60c3-43e2-ba40-4cc66b11739a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] create details page correspond to the wireframe.
- [x] create DOM tree that renders clicked pokemon image and data of pokemon
- [x] create function to get pokemon's data from pokeApi.
- [x] be able to collect pokemon's data by their id.
- [x] add click event listener for images.
- [x] match the click event with the images, so that correct detail information can be seen.
- [x] give id value to each `<li>`.
- [x] using id's from each `<li>`, set a 'click' event listener to match event.target's id.
- [x] if event.target matches, switch view to show details of clicked pokemon.
- [x] create click event handler for 'back to list' button. 
- [x] create click event callback function that goes back to pokelist page.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
