### ISSUE TITLE
Feature: User can store their favorite pokemon into ‘Favorites’ section

### ISSUE THREAD

**Issue by m-Cho1** [m-Cho1/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can store their favorite Pokémon into ‘Favorites’ page

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can click on + sign in details page, adding their favorite Pokémon to favorites page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/96744088/164875214-561ea37f-0d1e-40b3-aa02-e36bcb43fbe5.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create favorites page correspond to wireframe.
- [x] Add click event listener to + button, **and**
   - [x] for callback function, create modal with message "add to favorites?" with two button, confirm and cancel.
   - [x] Add click event listener to cancel button, go back to details page as a callback function.
   - [x] Add click event listener to confirm button, adding current pokemon to favorites page.
- [x] create localStorage in data.js for saving favorite pokemon data.
   - [x] Add the `nextEntryId` to the data object. (data.js).
   - [x] Increment the `nextEntryId` on the data model.
   - [x] Prepend the new object to the entries in the data model.
   - [x] Verify that favorite pokemon entries are saved to local storage along with the rest of the data model on page reload.
- [x] Verify that each new favorite pokemon entry receives an incrementing `nextFavoriteId`.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
