### ISSUE TITLE
Feature: User can view their ‘Favorites’ section

### ISSUE THREAD

**Issue by m-Cho1** [m-Cho1/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their ‘Favorites’ section

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can go to Favorites page to see their selected favorite Pokémon

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/96744088/165206018-4c6b636f-e47f-4950-9bad-0f49e37ddea0.png)
![image](https://user-images.githubusercontent.com/96744088/165206073-199217ad-a64b-401b-9adb-bc842d96d856.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add an empty `<ul>` element to the favorites page `<div>`.
- [x] create favorites page HTML structure with dummy data correspond to the wireframe.
- [x] check that the favorites list looks good on both mobile and desktop screens.
- [x] Define a function that takes a single pokemon data object from favoritePokemonList and returns a DOM tree that matches the dummy data design
- [x] Use a loop to create a DOM tree for each saved pokeData.currentPokemon in the data.favoritePokemonList from local storage in the favorites page.
- [x] Remove the example HTML dummy data once the favorite pokemon data is successfully being appended to the DOM on page load.
- [x] Add a navigation item to the navbar for Favorites.
- [x] Ensure that adding new favorite Pokemon also creates a new DOM tree for it an adds it to the favorites page.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
